src/Web/CommunityBox.Web.Mvc/ViewModels/Identities/LogInViewModel.cs
namespace CommunityBox.Web.Mvc.ViewModels.Identities
{
    public class LogInViewModel
    {
        public string Email { get; set; }
        
        public string Password { get; set; }
    }
}

src/Web/CommunityBox.Web.Mvc/ViewModels/Identities/UserViewModel.cs
using System;

namespace CommunityBox.Web.Mvc.ViewModels.Identities
{
    public class UserViewModel
    {
        public string Id { get; set; }
        
        public string UserName { get; set; }
        
        public string Email { get; set; }
        
        public string PhoneNumber { get; set; }
        
        public DateTime CreationUtcDate { get; set; }
        
        public DateTime? UpdateUtcDate { get; set; }

        public UserPersonalInformationViewModel UserPersonalInformation { get; set; }

        public bool IsMyProfile { get; set; }
    }
}

src/Web/CommunityBox.Web.Mvc/Controllers/ChatsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CommunityBox.ChatService.Api.Proto;
using CommunityBox.Web.Mvc.Clients.Chat;
using CommunityBox.Web.Mvc.ViewModels.Chat;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CommunityBox.Web.Mvc.Controllers
{
    [Authorize]
    public class ChatsController : Controller
    {
        private readonly IChatGrpcService _chatGrpcClient;
        private readonly IMapper _mapper;

        public ChatsController(IChatGrpcService chatGrpcClient, IMapper mapper)
        {
            _chatGrpcClient = chatGrpcClient;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = GetUserId();

            var response = await _chatGrpcClient.GetChatsAsync(userId);
            var retval = _mapper.Map<IReadOnlyCollection<ChatPreviewViewModel>>(response);

            return View(retval);
        }
        
        [HttpPost]
        public async Task<IActionResult> SendSingleMessage(NewSingleMessageViewModel viewModel)
        {
            var userId = GetUserId();

            var requestModel = _mapper.Map<NewSingleMessageModel>(viewModel);
            requestModel.UserId = userId;
            
            await _chatGrpcClient.SendMessageAsync(requestModel);
            return Ok();
        }

        public string GetUserId() =>
            User.Claims.FirstOrDefault(f => f.Type == "uid")?.Value;
    }
}

src/Web/CommunityBox.Web.Mvc/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using CommunityBox.Api.WebContracts.Identities;
using CommunityBox.Web.Mvc.Clients.Gateway;
using CommunityBox.Web.Mvc.ViewModels.Identities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CommunityBox.Web.Mvc.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        public const string Route = "User";
        private readonly IGatewayClient _gatewayClient;
        private readonly IMapper _mapper;

        public UserController(IGatewayClient gatewayClient, IMapper mapper)
        {
            _gatewayClient = gatewayClient;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] string userId)
        {
            if (userId == null)
                return RedirectToAction("Error", "Home");
            
            var user = await _gatewayClient.GetUserAsync(userId);

            if (user == null)
                return RedirectToAction("Error", "Home");
            
            var retval = _mapper.Map<UserViewModel>(user);

            if (userId == User.Claims.First(f => f.Type == "uid").Value)
                retval.IsMyProfile = true;
            
            return View(retval);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogIn(LogInViewModel viewModel)
        {
            var request = _mapper.Map<LogInContract>(viewModel);
            var response = await _gatewayClient.AuthAsync(request);
            var auth = _mapper.Map<AuthViewModel>(response);

            await AuthenticateAsync(auth);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        private async Task AuthenticateAsync(AuthViewModel auth)
        {
            var claims = new List<Claim>
            {
                new("uid", auth.UserId),
                new("token", auth.Token),
                new("email", auth.Email)
            };

            var id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType,
                ClaimsIdentity.DefaultRoleClaimType);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }
    }
}

src/Web/CommunityBox.Web.Mvc/Views/User/Index.cshtml
@model CommunityBox.Web.Mvc.ViewModels.Identities.UserViewModel

@section Scripts{
<script xmlns="http://www.w3.org/1999/html">
        // Get the modal
        const modal = document.getElementById("chatModal");
        
        // Get the button that opens the modal
        const btn = document.getElementById("myBtn");
        
        // Get the <span> element that closes the modal
        const span = document.getElementsByClassName("close")[0];
        
        // When the user clicks the button, open the modal 
        btn.onclick = function() {
          modal.style.display = "block";
        }
        
        // When the user clicks on <span> (x), close the modal
        span.onclick = function() {
          modal.style.display = "none";
        }
        
        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
          if (event.target === modal) {
            modal.style.display = "none";
          }
        }
    </script>

<script>
        $("#sendMsg").click(function(){
            const requestData = {
              RecipientUserId: $("#RecipientUserId").val(),
              Content: $("#Content").val()
            };
            
            $.ajax({
                url: '@Url.Action("SendSingleMessage", "Chats")',
                method: 'POST',
                data: requestData,
                success: function(data){
                    const modal = document.getElementById("chatModal");
                    modal.style.display = "none";
                    $("#Content").val('');
                }
            });
        });
</script>
}

@section Styles{
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
        body {font-family: Arial, Helvetica, sans-serif;}
        
        /* The Modal (background) */
        .modal {
          display: none; /* Hidden by default */
          position: fixed; /* Stay in place */
          z-index: 1; /* Sit on top */
          padding-top: 100px; /* Location of the box */
          left: 0;
          top: 0;
          width: 100%; /* Full width */
          height: 100%; /* Full height */
          overflow: auto; /* Enable scroll if needed */
          background-color: rgb(0,0,0); /* Fallback color */
          background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }
        
        /* Modal Content */
        .modal-content {
          background-color: #fefefe;
          margin: auto;
          padding: 20px;
          border: 1px solid #888;
          width: 80%;
        }
        
        /* The Close Button */
        .close {
          color: #aaaaaa;
          float: right;
          font-size: 28px;
          font-weight: bold;
        }
        
        .close:hover,
        .close:focus {
          color: #000;
          text-decoration: none;
          cursor: pointer;
        }
    </style>
}

<div class="form-group">
    <label asp-for="UserName">Имя</label>
    <input type="text" asp-for="UserName" class="form-control" disabled/>
</div>
<div class="form-group">
    <label asp-for="Id">Id</label>
    <input type="text" asp-for="Id" class="form-control" disabled/>
</div>
<div class="form-group">
    <label asp-for="Email">Описание лота</label>
    <input type="text" asp-for="Email" class="form-control" disabled/>
</div>
<br/>
<a href="@Url.Action("List","Auction", new {id = Model.Id})" class="form-control btn-primary text-center" role="button">Аукционы</a>
<br/>

@if (!Model.IsMyProfile)
{
    <button id="myBtn" class="form-control btn-secondary">Написать сообщение</button>
    
    <div class="container">
        <div id="chatModal" class="modal">

            <div class="modal-content">
                <span class="close">&times;</span>
                <div id="chatForm">
                    <input type="hidden" value="@Model.Id" id="RecipientUserId" name="RecipientUserId">
                    <textarea style="height: 150px !important;" class="form-control" id="Content" name="Content"></textarea>
                    <br/>
                    <button id="sendMsg" type="submit" class="form-control btn-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>
}

src/Web/CommunityBox.Web.Mvc/Views/User/LogIn.cshtml
@model CommunityBox.Web.Mvc.ViewModels.Identities.LogInViewModel;

<div class="container">
    <form asp-action="LogIn" asp-controller="User" asp-anti-forgery="true">
        <div>
            <div class="form-group">
                <label asp-for="Email">Введите Email</label>
                <input type="text" asp-for="Email" class="form-control" value="string"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password">Введите пароль</label>
                <input type="password" asp-for="Password" class="form-control" value="Qwerty123!"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Войти" class="form-control  bLightBlu"/>
            </div>
        </div>
    </form>
</div>